## Second Module

## 1. Numpy

* Numpy is a powerful Python package for manipulating numeric data structures called **arrays**.<br>
* The basic object in NumPy is the array, which is conceptually similar to a matrix. The NumPy array class is called ndarray (for "n-dimensional array").<br>
* The vector and matrix are examples of arrays<br>
* The name numpy means "Numeric Python" <br>
* Numpys are quite similar to lists, but they have an additional feature: it can perform calculations on integer arrays

### Array Creation

In [4]:
# import numpy as np
import numpy as np

In [5]:
# LIST 
b = [1,2,3,4,5,6]
b

[1, 2, 3, 4, 5, 6]

In [39]:
# 1-D ARRAY
a = np.array([1.,2.,3.,4.,5.])
a

array([1., 2., 3., 4., 5.])

In [7]:
c = np.array([2,3,5,7,11])
c

array([ 2,  3,  5,  7, 11])

In [8]:
# 2-D ARRAY 
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [9]:
e = np.array([[2,3,4],[5,9,10]])
e

array([[ 2,  3,  4],
       [ 5,  9, 10]])

In [10]:
# 3-D ARRAY
f = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,20,23]]])
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 20, 23]]])

![Dimensions](https://i1.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1)


### Basic Array Operations

In [11]:
# Addition
lista1 = [1,2,3] 
lista2 = [4,5,6]
lista1 + lista2

[1, 2, 3, 4, 5, 6]

In [12]:
lista1*4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
integer1 = np.array([1,2,3])
integer2 = np.array([4,5,6])
integer1 + integer2

array([5, 7, 9])

In [14]:
integer1 * 2

array([2, 4, 6])

In [15]:
integer2 * 4

array([16, 20, 24])

### Array Atributtes 

|Atributtes|Description|
|----------|-----------|
|dtype     | The type of the elements in the array|
|ndim      |The number of axes(dimensions) of the array|
|shape     |A tuple of integers indicating the size in each dimension|
|size      |The total number of elements in the array|

In [40]:
#dtype
a.dtype



dtype('float64')

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
c.dtype

dtype('int32')

In [19]:
#ndim
a.ndim

1

In [20]:
d

array([[1, 2],
       [3, 4]])

In [24]:
d.ndim

2

In [25]:
f.ndim

3

In [26]:
#shape
a.shape

(5,)

In [27]:
a1 = np.array([[2,3],[5,6]])
a1

array([[2, 3],
       [5, 6]])

In [28]:
a1.shape

(2, 2)

In [30]:
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 20, 23]]])

In [29]:
f.shape

(2, 2, 3)

In [31]:
#size
a.size

5

In [43]:
len(a)

5

In [35]:
g = np.array(["hola","peruu"])
g

array(['hola', 'peruu'], dtype='<U5')

In [36]:
g.size

2

In [42]:
len(g)

2

In [37]:
f

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 20, 23]]])

In [38]:
f.size

12

In [41]:
len(f)

2

### Basic Array Operations

![type_of_matrix](https://www.onlinemathlearning.com/image-files/types-of-matrices.png)


### Array Creation Routines

Numpy provides efficient ways to create certain commonly-used arrays

|Function|Returns|
|--------|-------|
|arange( )|Array of sequential integers (like list(range( )))|
|ones( )|Array of given shape and type, filled with ones|
|ones_like( )|Array of ones with the same shape and type as a given array|
|zeros( )|Array of given shpe and type, filled with zeros|
|zeros_like( )|Array of zeros with the same shape and type|
|full( )|Array of given shape and type, filled with a specified value|
|full_like( )|Full array with the same shape and type as a given array|

In [44]:
# A 1-D array of 4 zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [45]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [47]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
# full
np.full(2,3)

array([3, 3])

In [49]:
np.full((2,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [50]:
a1 = np.array([[2,3],[5,6]])
a1

array([[2, 3],
       [5, 6]])

In [52]:
a2 = np.array([[2,3,4],[5,7,6],[10,11,12]])
a2

array([[ 2,  3,  4],
       [ 5,  7,  6],
       [10, 11, 12]])

In [53]:
a3 = np.array([1,2,3,4,5,6,7,9])
a3

array([1, 2, 3, 4, 5, 6, 7, 9])

In [54]:
# zeros_like
b1 = np.zeros_like(a1)
b1

array([[0, 0],
       [0, 0]])

In [55]:
# ones_like
b2 = np.ones_like(a3)
b2

array([1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
# np.full_like
b3 = np.full_like(a2,-1)
b3

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

### numpy.arange

numpy.arange([start,] stop, [step, ] dtype = None) <br>

The first of the 3 parameters determines the range of the values, while the fourth specifies the type of the elements:
    
   **1. start :** is the number (integer or decimal) that defines the first value in the array.<br>
 **2. stop:** is the number that defines the end of the array; and is not included in the array.<br>
 **3. step:** is the number that defines the spacing (difference) between every 2 consecutive values in the array and the default value is 1.<br>
 **4. dtype:** is the type of the array output elements and defaults to None.

In [58]:
c1 = np.arange(start = 1, stop = 13, step = 2)
c1 

array([ 1,  3,  5,  7,  9, 11])

In [59]:
c2 = np.arange(1,10,2)
c2

array([1, 3, 5, 7, 9])

In [62]:
c3 = np.arange(1.2,10.9,1.5)
c3

array([ 1.2,  2.7,  4.2,  5.7,  7.2,  8.7, 10.2])

In [64]:
c4 = np.arange(100., 150., 7.)
c4

array([100., 107., 114., 121., 128., 135., 142., 149.])

more array creation: http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

### Array Slicing

In [65]:
d = np.arange(12)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
d[3]

3

In [67]:
d[5]

5

In [68]:
d[:3]

array([0, 1, 2])

In [69]:
d1 = np.array(['a','s','b','luis'])
d1

array(['a', 's', 'b', 'luis'], dtype='<U4')

In [70]:
d1[3]

'luis'

In [72]:
d1[0]

'a'

In [73]:
d1[:2]

array(['a', 's'], dtype='<U4')

In [74]:
d1[:]

array(['a', 's', 'b', 'luis'], dtype='<U4')

In [75]:
d2 = np.array([[0,1,2,3],[4,5,6,7]])
d2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
d2[1,3]

7

In [77]:
d2[0,2]

2

In [78]:
d2[:,0]

array([0, 4])

In [79]:
d2[:,1:] 

array([[1, 2, 3],
       [5, 6, 7]])

In [80]:
d3 = np.array([[10,14,28],[21 ,24,30],[17,49,98]])
d3

array([[10, 14, 28],
       [21, 24, 30],
       [17, 49, 98]])

In [81]:
d3[1:,0]

array([21, 17])

In [82]:
d3[2,:]

array([17, 49, 98])

In [83]:
d3[1:,:]

array([[21, 24, 30],
       [17, 49, 98]])

### Array Manipulation

#### Shaping

In [84]:
e = np.arange(15)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
e.size

15

In [89]:
e.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [87]:
e.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
f = np.arange(0,24,2)
f

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [91]:
f.size

12

In [92]:
f.reshape((4,3))

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [93]:
f.reshape((6,2))


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [94]:
f.reshape((2,6))


array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

#### Stacking

|Function|Description|
|--------|-----------|
|concatenate( )|Join a sequence of arrays along an existing axis|
|hstack( )|Stack arrays in sequence horizontally(column wise)|
|vstack( )|Stack arrays in sequence vertically(row wise)|
|column_stack( )|Stack 1-D arrays as columns into a 2-D array|

In [99]:
g = np.array([[5,6],[7,8]])
h = np.array([[1,2]])
np.concatenate((g,h), axis = 0)

array([[5, 6],
       [7, 8],
       [1, 2]])

In [96]:
g

array([[5, 6],
       [7, 8]])

In [97]:
h

array([[1, 2]])

In [100]:
h.shape

(1, 2)

In [101]:
h.T

array([[1],
       [2]])

In [102]:
i = np.array([[10],[11]])
i

array([[10],
       [11]])

In [103]:
i.shape

(2, 1)

In [104]:
g

array([[5, 6],
       [7, 8]])

In [105]:
g.shape

(2, 2)

In [106]:
np.concatenate((g,i), axis = 1)

array([[ 5,  6, 10],
       [ 7,  8, 11]])

In [107]:
mat1 = np.arange(1,13,2).reshape((2,3))
mat1

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [108]:
mat2 = np.zeros((4,3))
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
# vstack()
mat3 = np.vstack((mat1,mat2))
mat3

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [111]:
mat4 = np.vstack((mat1,mat2,mat1))
mat4

array([[ 1.,  3.,  5.],
       [ 7.,  9., 11.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  3.,  5.],
       [ 7.,  9., 11.]])

In [112]:
mat4.shape

(8, 3)

In [113]:
# hstack()
mat5 = np.array([[1,7],[3,9],[5,11]])
mat5

array([[ 1,  7],
       [ 3,  9],
       [ 5, 11]])

In [116]:
mat5.shape

(3, 2)

In [114]:
mat6 = np.ones((3,4))
mat6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
mat6.shape

(3, 4)

In [115]:
mat7 = np.hstack((mat5,mat6))
mat7

array([[ 1.,  7.,  1.,  1.,  1.,  1.],
       [ 3.,  9.,  1.,  1.,  1.,  1.],
       [ 5., 11.,  1.,  1.,  1.,  1.]])

#### max ( ) , min ( ), sum ( )

In [118]:
k = np.array([[4,2,6],[1,5,3]])
k

array([[4, 2, 6],
       [1, 5, 3]])

In [119]:
np.max(k)

6

In [120]:
# Find the maximum value of each column.

np.max(k, axis = 0)

array([4, 5, 6])

In [122]:
# Find the maximum value of each row.
np.max(k, axis = 1)

array([6, 5])

In [123]:
np.min(k)

1

In [129]:
k

array([[4, 2, 6],
       [1, 5, 3]])

In [125]:
# Find the minimum value of each column.
np.min(k, axis = 0)

array([1, 2, 3])

In [126]:
np.min(k, axis = 1)

array([2, 1])

In [127]:
np.sum(k, axis = 1)

array([12,  9])

In [128]:
np.sum(k, axis = 0)

array([5, 7, 9])

|Function|Description|
|--------|-----------|
|abs() or absolute()|Calculate the absolute value element-wise|
|exp()/log()|Exponential(e^x)/natural log element-wise|
|sqrt()|The positive square-root, element-wise|
|sin(), cos(), tan()|Element-wise trigonometric operations|

In [130]:
find_abs = np.arange(-2,3)
find_abs

array([-2, -1,  0,  1,  2])

In [131]:
print(find_abs, np.abs(find_abs))

[-2 -1  0  1  2] [2 1 0 1 2]


In [132]:
find_log = [10,100,10000,100000] # natural log 
print(find_log,np.log(find_log))

[10, 100, 10000, 100000] [ 2.30258509  4.60517019  9.21034037 11.51292546]


### Other array methods

|method|Returns|
|------|-------|
|max() |The maximum element of the array.|
|mean()| The average value of the array.|
|min()| The minimum element of the array.|
|sort()| Return nothing; sort the array in-place.|
|std() |The standard deviation of the array.|
|sum() |The sum of the elements of the array.|
|var()| The variance of the array||