In [9]:
import numpy as np

In [2]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])

In [3]:
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [4]:
#Pregunta 1
a = np.array([6,0,0,0])
b = np.array([6,6,0,0])
c = np.array([6,6,6,0])
d = np.array([6,6,6,6])
print(a, b, c, d)

[6 0 0 0] [6 6 0 0] [6 6 6 0] [6 6 6 6]


In [5]:

A = np.concatenate((a,b,c,d), axis = 0)


In [6]:
A

array([6, 0, 0, 0, 6, 6, 0, 0, 6, 6, 6, 0, 6, 6, 6, 6])

In [7]:
A.reshape((4,4))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [8]:
#Pregunta 2
a1 = np.arange(start=2, stop=33, step=2)
a1
a1.reshape(4,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [9]:
#Pregunta 3
a2 = np.arange(start=1, stop=24, step=2)
a2
a2.reshape(4,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [10]:
#Pregunta 4
a3 = np.arange(32)

In [11]:
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [12]:
#Pregunta 4.2
a3.reshape(16,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [13]:
#Pregunta 4.3
a3.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
#Pregunta 4.4
a3.reshape(2,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [15]:
task = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])

In [16]:
task

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [17]:
#Pregunta 5
a = np.array([2,2,2,2,2])
b = np.array([2,0,0,0,2])
c = np.array([2,0,16,0,2])
d = np.array([2,0,0,0,2])
e = np.array([2,2,2,2,2])
print(a,b,c,d,e)

[2 2 2 2 2] [2 0 0 0 2] [ 2  0 16  0  2] [2 0 0 0 2] [2 2 2 2 2]


In [18]:
Z = np.concatenate((a,b,c,d,e), axis=0)

In [19]:
Z

array([ 2,  2,  2,  2,  2,  2,  0,  0,  0,  2,  2,  0, 16,  0,  2,  2,  0,
        0,  0,  2,  2,  2,  2,  2,  2])

In [20]:
Z.reshape((5,5))

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [22]:
#Pregunta #1
D = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])

In [23]:
D

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [8]:
m1=np.full((4,4),6) 
np.tril(m1)

NameError: name 'np' is not defined

In [25]:
B = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]])

In [26]:
B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [27]:
O= np.arange(2,34,2).reshape(4,4)

In [28]:
O

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [5]:
#P4 Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [10]:
N= np.arange(2,34,1)

In [11]:
N

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [12]:
N.size

32

In [13]:
N.reshape((2,16))

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [14]:
N.reshape((4,8))

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33]])

In [15]:
N.reshape((8,4))

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [16]:
N.reshape((16,2))

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33]])

In [28]:
#p4

In [29]:
C = np.arange(1,25,2).reshape(4,3)

In [30]:
C

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [17]:
#P5

In [19]:
test= np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])

In [20]:
test

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [21]:
# Primera forma
t1 = np.array([[2,2,2,2,2],[2,0,0,0,2]])

In [22]:
t1

array([[2, 2, 2, 2, 2],
       [2, 0, 0, 0, 2]])

In [23]:
t2 = np.array([[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])

In [24]:
t2

array([[ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [26]:
t3 = np.concatenate((t1,t2), axis=0 )

In [27]:
t3

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])