# Tarea 3
### Alvaro Palma

In [1]:
import numpy as np

In [2]:
#Pregunta 1
a = np.array([6,0,0,0])
b = np.array([6,6,0,0])
c = np.array([6,6,6,0])
d = np.array([6,6,6,6])
print(a, b, c, d)

[6 0 0 0] [6 6 0 0] [6 6 6 0] [6 6 6 6]


In [3]:
Z = np.concatenate((a,b,c,d), axis = 0)
Z

array([6, 0, 0, 0, 6, 6, 0, 0, 6, 6, 6, 0, 6, 6, 6, 6])

In [4]:
Z.reshape((4,4))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [5]:
#Otra manera
np.vstack((a,b,c,d))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [6]:
#Pregunta 2
a1 = np.arange(start = 2, stop = 33, step = 2)
a1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [7]:
a1.reshape((4,4))

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [8]:
#Pregunta 3
a2 = np.arange(start=1, stop = 24, step=2)
a2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [9]:
a2.reshape((4,3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [10]:
#Pregunta 4
a3 = np.arange(32)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [11]:
#forma1
a3.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [12]:
#forma2
a3.reshape((16,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [13]:
#forma3
a3.reshape((1,32))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [14]:
#forma4
a3.reshape((2,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [15]:
#Pregunta 5
a4 = np.eye(5, dtype=int)
a4

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
a5 = np.full_like(a4,2)
a5

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [17]:
a5[(1,1)] = 0
a5[(1,2)] = 0
a5[(1,3)] = 0
a5[(2,1)] = 0
a5[(2,2)] = 16
a5[(2,3)] = 0
a5[(3,1)]= 0
a5[(3,2)]= 0
a5[(3,3)]= 0
a5

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])