### N1

In [2]:
import numpy as np

In [3]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

### N2

Crear un array de 4x4 con valores pares

In [13]:
a= np.array(range(0,16))
a1=np.array(range(0,16))*2
a2=a1.reshape((4,4))
a2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

### N3

Crear un array de 4x3 con valores impares

In [15]:
b1=np.array(range(0,12))*2
b2=b1+1
b3=b2.reshape((4,3))
b3

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

### N4

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [26]:
c1=np.array(range(0,32))
c2=c1.reshape((32,1))
c3=c1.reshape((2,16))
c4=c1.reshape((4,8))
c5=c1.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### N5

In [3]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [32]:
d=np.full((5,5),2)
d1=d[1:4,1:4]=0
d2=d[2,2]=16
d

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])