In [2]:
import numpy as np

In [4]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [5]:
#Pregunta 1
a = np.array([6,0,0,0])
b = np.array([6,6,0,0])
c = np.array([6,6,6,0])
d = np.array([6,6,6,6])
print(a, b, c, d)

[6 0 0 0] [6 6 0 0] [6 6 6 0] [6 6 6 6]


In [6]:
A = np.concatenate((a,b,c,d), axis = 0)
A

array([6, 0, 0, 0, 6, 6, 0, 0, 6, 6, 6, 0, 6, 6, 6, 6])

In [7]:
A.reshape((4,4))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [8]:
#Pregunta 2
a1 = np.arange(start=2, stop=33, step=2)
a1
a1.reshape(4,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [9]:
#Pregunta 3
a2 = np.arange(start=1, stop=24, step=2)
a2
a2.reshape(4,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [10]:
#Pregunta 4
a3 = np.arange(32)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [11]:
#Pregunta 4.1
a3.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [12]:
#Pregunta 4.2
a3.reshape(16,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [13]:
#Pregunta 4.3
a3.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
#Pregunta 4.4
a3.reshape(2,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [15]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [16]:
#Pregunta 5
a = np.array([2,2,2,2,2])
b = np.array([2,0,0,0,2])
c = np.array([2,0,16,0,2])
d = np.array([2,0,0,0,2])
e = np.array([2,2,2,2,2])
print(a,b,c,d,e)

[2 2 2 2 2] [2 0 0 0 2] [ 2  0 16  0  2] [2 0 0 0 2] [2 2 2 2 2]


In [17]:
Z = np.concatenate((a,b,c,d,e), axis=0)
Z

array([ 2,  2,  2,  2,  2,  2,  0,  0,  0,  2,  2,  0, 16,  0,  2,  2,  0,
        0,  0,  2,  2,  2,  2,  2,  2])

In [18]:
Z.reshape((5,5))

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

Ivan del Aguila

Pregunta #1

In [3]:
D = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
D

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [4]:
m1=np.full((4,4),6)
np.tril(m1)


array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

Pregunta #2

Crear un array de 4x4 con valores pares


In [8]:
B = np.array([[2,4,6,8],[10,12,14,16],[18,20,22,24],[26,28,30,32]])
B


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [9]:
O= np.arange(2,34,2).reshape(4,4)
O


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

Pregunta #3

Crear un array de 4x3 con valores impares


In [10]:
Q = np.arange(1,25,2).reshape(4,3)
Q


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

Pregunta #4

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente


In [11]:
N= np.arange(2,34,1)
N


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [12]:
N.size

32

In [13]:
N.reshape((2,16))


array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [14]:
N.reshape((4,8))

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33]])

In [15]:
N.reshape((8,4))

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [16]:
N.reshape((16,2))

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33]])

Pregunta #5

In [17]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea


array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [18]:
# Primera forma
tarea_1 = np.array([[2,2,2,2,2],[2,0,0,0,2]])
tarea_1


array([[2, 2, 2, 2, 2],
       [2, 0, 0, 0, 2]])

In [19]:
tarea_2 = np.array([[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea_2


array([[ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [20]:
tarea_3 = np.concatenate((tarea_1,tarea_2), axis=0 )
tarea_3


array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [7]:
#FranclinUg
import numpy as np

In [8]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [9]:
#Pregunta1
q = np.array([6,0,0,0])
w = np.array([6,6,0,0])
e = np.array([6,6,6,0])
r = np.array([6,6,6,6])
print(q, w, e, r)

[6 0 0 0] [6 6 0 0] [6 6 6 0] [6 6 6 6]


In [11]:
A = np.concatenate((q,w,e,r), axis = 0)
A

array([6, 0, 0, 0, 6, 6, 0, 0, 6, 6, 6, 0, 6, 6, 6, 6])

In [12]:
A.reshape((4,4))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [17]:
#Pregunta2
B = np.array([[4,8,12,16],[20,24,28,32],[36,40,44,48],[52,56,60,64]])
B

array([[ 4,  8, 12, 16],
       [20, 24, 28, 32],
       [36, 40, 44, 48],
       [52, 56, 60, 64]])

In [18]:
#pregunta3
F = np.arange(1,25,2).reshape(4,3)
F

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])

In [20]:
#pregunta4
X = np.arange(2,34)
X

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [21]:
X.size

32

In [23]:
X.reshape ((2,16 ))

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [26]:
X.reshape ((4,8))

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33]])

In [28]:
X.reshape ((16,2))

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33]])

In [29]:
X.reshape ((8,4))

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [31]:
#pregunta5
q = np.array([2,2,2,2,2])
w = np.array([2,0,0,0,2])
e = np.array([2,0,16,0,2])
r = np.array([2,0,0,0,2])
t = np.array([2,2,2,2,2])
print(q,w,e,r,t)

[2 2 2 2 2] [2 0 0 0 2] [ 2  0 16  0  2] [2 0 0 0 2] [2 2 2 2 2]


In [36]:
fug = np.concatenate((q,w,e,r,t), axis=0)
fug

array([ 2,  2,  2,  2,  2,  2,  0,  0,  0,  2,  2,  0, 16,  0,  2,  2,  0,
        0,  0,  2,  2,  2,  2,  2,  2])

In [37]:
fug.reshape((5,5))

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [ ]:
#FranclinUg