# Tarea 3
### Alvaro Palma

In [ ]:
import numpy as np

In [ ]:
#Pregunta 1
a = np.array([6,0,0,0])
b = np.array([6,6,0,0])
c = np.array([6,6,6,0])
d = np.array([6,6,6,6])
print(a, b, c, d)

In [ ]:
Z = np.concatenate((a,b,c,d), axis = 0)
Z

In [ ]:
Z.reshape((4,4))

In [ ]:
#Otra manera
np.vstack((a,b,c,d))

In [ ]:
#Pregunta 2
a1 = np.arange(start = 2, stop = 33, step = 2)
a1

In [ ]:
a1.reshape((4,4))

In [ ]:
#Pregunta 3
a2 = np.arange(start=1, stop = 24, step=2)
a2

In [ ]:
a2.reshape((4,3))

In [ ]:
#Pregunta 4
a3 = np.arange(32)
a3

In [ ]:
#forma1
a3.reshape((8,4))

In [ ]:
#forma2
a3.reshape((16,2))

In [ ]:
#forma3
a3.reshape((1,32))

In [ ]:
#forma4
a3.reshape((2,16))

In [ ]:
#Pregunta 5
a4 = np.eye(5, dtype=int)
a4

In [ ]:
a5 = np.full_like(a4,2)
a5

In [ ]:
a5[(1,1)] = 0
a5[(1,2)] = 0
a5[(1,3)] = 0
a5[(2,1)] = 0
a5[(2,2)] = 16
a5[(2,3)] = 0
a5[(3,1)]= 0
a5[(3,2)]= 0
a5[(3,3)]= 0
a5

### ------------------------------------------------------------------------------------------------------------------------

### ARLETHE ARONES RONDON - TAREA 3

### N1


In [ ]:
import numpy as np


In [ ]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

In [ ]:
A2= np.tri(4,None,0,dtype= "int")
A2*6

### N2

Crear un array de 4x4 con valores pares

In [ ]:
B = np.arange(0,31,2)
B.reshape((4,4))

### N3

Crear un array de 4x3 con valores impares

In [ ]:
C = np.arange(1,24,2)
C.reshape((4,3))

### N4

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [ ]:
D = np.arange(1,33,1)
M = D.reshape((4,8))
N = D.reshape((8,4))
O = D.reshape((16,2))
P = D.reshape((2,16))


In [ ]:
M

In [ ]:
N

In [ ]:
O

In [ ]:
P

### N5

In [ ]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

In [ ]:
X= np.full((5,5),2)
X

In [ ]:
X[1:4,1:4]=0
X

In [ ]:
X[2,2]=16
X

### ---------------------------------------------------------------------------------------------------------------------------

# Tarea 3 - Elibeth Cirilo

### N1

In [ ]:
import numpy as np

A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

**Solution**

One way is to create the matrix by hand.

In [ ]:
a_1 = np.array([6,0,0,0])
a_2 = np.array([6,6,0,0])
a_3 = np.array([6,6,6,0])
a_4 = np.array([6,6,6,6])
A = np.vstack((a_1, a_2, a_3, a_4))
A

Another way is to create an lower-triangle matrix from an array of four 6.

In [ ]:
sixs = [6,6,6,6]
A_1 = np.tril(sixs, k=0)
A_1

### N2

Crear un array de 4x4 con valores pares

__Solution__

In [ ]:
# creating an arrange of even values 
b_1 = np.arange(start = 6, stop = 37, step = 2)
len(b_1)

In [ ]:
# reshaping
B = b_1.reshape((4,4))
B

### N3

Crear un array de 4x3 con valores impares

__Solution__

In [ ]:
# creating an arrange of odd values 
c_1 = np.arange(start = 3, stop = 27, step = 2)
len(c_1)

In [ ]:
C = c_1.reshape((4,3))
C

### N4

Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

__Solution__

I will create an array of random numbers using <code>random</code> and <code>seed</code>.

In [ ]:
# generate random integer values
from random import seed
from random import randint
# seed random number generator
seed(2)
lista=[]
# generate some integers and add them to an array
for _ in range(32):
    value = randint(0, 100)
    lista.append(value)
    #print(value)
    #print(lista)
    arr = np.array(lista)
print(len(arr))
arr # has 32 values 

Once the array is created, we can reshape it in 4 different ways. 

In [ ]:
arr_1 = arr.reshape((2,16))
arr_1

In [ ]:
arr_2 = arr.reshape((4,8))
arr_2

In [ ]:
arr_3 = arr.reshape((8,4))
arr_3

In [ ]:
arr_4 = arr.reshape((32,1))
arr_4

### N5

In [ ]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

__Solution__

I will create an array full of 2, and then replace some values (zeros and sixteen).

In [ ]:
tarea = np.full((5,5),2)
tarea[1:4,1:4] = 0
tarea[2,2] = 16
tarea

### ---------------------------------------------------------------------------------------------------------------------------

# Task 3 - Brayahm Najarro 

In [35]:
import numpy as np

# N1

In [37]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

In [39]:
x= np.concatenate ((A), axis = 0)
x

array([6, 0, 0, 0, 6, 6, 0, 0, 6, 6, 6, 0, 6, 6, 6, 6])

In [40]:
x.reshape((4,4))

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

### N2  Crear un array de 4x4 con valores pares

In [20]:
x_1=np.arange(2,33,2)
x_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [21]:
x_1.reshape ((4,4))

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

### N3 Crear un array de 4x3 con valores impares

In [22]:
x_2=np.arange(1,33,2)
x_2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [23]:
x_2.reshape((4,4))

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

###  N4 Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [41]:
#Creamos el arange
elementos=np.arange(32)
elementos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [27]:
#Forma 1
elementos.reshape((4,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [28]:
#Forma 2
elementos.reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [29]:
#Forma 3
elementos.reshape((2,16))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [31]:
#Forma 4
elementos.reshape ((16,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

# N5

In [33]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [34]:
#Otra Forma
bn= np.array ([[3,3,2,3,3],[3,2,1,2,3],[2,1,0,1,2],[3,2,1,2,3],[3,3,2,3,3]])
bn

array([[3, 3, 2, 3, 3],
       [3, 2, 1, 2, 3],
       [2, 1, 0, 1, 2],
       [3, 2, 1, 2, 3],
       [3, 3, 2, 3, 3]])

# ---------